version: '3'

networks:
  uema_docker:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: uema_nginx
    volumes:
      - ./:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "7000:80"
    networks:
      - uema_docker

  db:
    image: postgres:14
    container_name: uema_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: base_uema
      POSTGRES_PASSWORD: postgres
    ports:
      - "3457:3452"
    networks:
      - uema_docker

  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html
    container_name: uema_php
    ports:
      - "9004:9004"
    networks:
      - uema_docker

  composer:
    image: composer:latest
    container_name: uema_composer
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - db
      - php
    networks:
      - uema_docker    
