version: '3'

#Rede
networks:
  uema_networks:
    driver: bridge

services:



  app:
    build:
      args:
        user: uema
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: uema_app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www/
    networks:
      - uema_networks


  nginx:
    image: nginx:stable-alpine
    restart: unless-stopped
    container_name: uema_nginx
    volumes:
      - ./:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8000:80"
    networks:
      - uema_networks

  db:
    image: postgres:14
    restart: unless-stopped
    container_name: uema_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: base_uema
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - uema_networks

  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html
    container_name: uema_php
    ports:
      - "9004:9004"
    networks:
      - uema_networks

  composer:
    image: composer:latest
    container_name: uema_composer
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - db
      - php
      - app
    networks:
      - uema_networks    

  artisan:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: uema_artisan
    volumes:
      - ./:/var/www
    depends_on:
      - postgres
    working_dir: /var/www/
    entrypoint: ['php', '/var/www/artisan']
    networks:
      - app-network
