version: '3'
services:

  #PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel/app
    container_name: registros-app
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www:delegated
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini:delegated
      - ~/.composer/docker-cache/:/root/.composer:cached
    networks:
      - registros-networks

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: registros-webserver
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www:delegated
      - ./nginx/conf.d/:/etc/nginx/conf.d/:delegated
    networks:
      - registros-networks
    depends_on:
      - postgres
      - app

  #Postgres Service
  postgres:
    container_name: registros-postgres
    image: postgres
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: /data/postgres
    volumes:
        - postgres:/data/postgres:delegated
    ports:
      - "5432:5432"
    networks:
      - registros-networks

  #PgAdmin
  pgadmin:
    container_name: registros-pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@registros.br
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
        - pgadmin:/root/.pgadmin
    ports:
      - "8080:80"
    networks:
      - registros-networks

    #composer
  composer:
    build:
      context: .
      dockerfile: Dockerfile-composer
    container_name: registros-composer
    volumes:
      - ./:/var/www/
    working_dir: /var/www/
    depends_on:
      - app
    networks:
      - registros-networks

  #npm
  npm:
    image: node:13.7
    container_name: registros-npm
    volumes:
      - ./:/var/www/
    working_dir: /var/www/
    entrypoint: ['npm']
    networks:
      - registros-networks

  #artisan
  artisan:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: registros-artisan
    volumes:
      - ./:/var/www
    depends_on:
      - postgres
    working_dir: /var/www/
    entrypoint: ['php', '/var/www/artisan']
    networks:
      - registros-networks

#Docker Networks
networks:
  registros-networks:
    driver: bridge

#Volumes
volumes:
  dbdata:
    driver: local
  postgres:
  pgadmin: