<?php
return [

    'ppgraduacao' => [
        'AGRICULTURA E AMBIENTE', 'AGROECOLOGIA', 'BIODIVERSIDADE, AMBIENTE E SAÚDE', 'BIODIVERSIDADE E BIOTECNOLOGIA DA AMAZÔNIA LEGAL - REDE BIONORTE',
        'CARTOGRAFIA SOCIAL E POLÍTICA DA AMAZÔNIA', 'CIÊNCIA ANIMAL', 'DEFESA SANITÁRIA ANIMAL', 'DESENVOLVIMENTO SOCIOESPACIAL E REGIONAL', 'ECOLOGIA E CONSERVAÇÃO DA BIODIVERSIDADE',
        'EDUCAÇÃO', 'EDUCAÇÃO INCLUSIVA - REDE PROFEI', 'ENGENHARIA AEROESPACIAL RNA - REDE', 'ENGENHARIA DA COMPUTAÇÃO E SISTEMAS', 'GEOGRAFIA, NATUREZA E DINÂMICA DO ESPAÇO',
        'HISTÓRIA', 'LETRAS', 'MATEMÁTICA - REDE PROFMAT'
    ]
];
